on:
  workflow_call

 
jobs:
  run-script:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
 
    - name: Checkout another repository
      uses: actions/checkout@v2
      with:
        repository: jyotika23/pythonproject # Replace 'owner/other-repo' with the actual owner and repo name
        token: ${{ secrets.gittoken }}  # Use the secret to access the other repository
        path: other-repo              # Specify a folder to checkout the repository into
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version needed
 
    # - name: Install dependencies
    #   run: |
    #     cd other-repo
    #     pip install -r requirements.txt  # Install any required dependencies
 
    - name: Run Python script
      run: |
        cd other-repo
        python script.py  # Execute the script from the other repository
